apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: frontend-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - shoppingapp.lvnlab.internal
    tls:
      mode: SIMPLE
      credentialName: frontend-credential
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: frontend-vs
  namespace: webapps
spec:
  hosts:
  - shoppingapp.lvnlab.internal
  gateways:
  - frontend-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend.webapps.svc.cluster.local
        port:
          number: 80
